version: "3.9"
volumes:
  pg_constellar:

services:
  db_for_rally:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: constellar-db
      POSTGRES_USER: denis
      POSTGRES_PASSWORD: starbest2003
    volumes:
      - pg_constellar:/var/lib/postgresql/data
    ports:
      - "5410:5432"